-- phpMyAdmin SQL Dump
-- version 4.9.5deb2
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : ven. 13 mai 2022 à 16:23
-- Version du serveur :  10.3.34-MariaDB-0ubuntu0.20.04.1
-- Version de PHP : 7.4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Base de données : `storyofyourlife`
--

--

--
-- Déchargement des données de la table `histoire`
--

INSERT INTO `histoire` (`hist_id`, `titre`, `cache`, `nb_vie_dbt`, `nb_joue`, `nb_gagne`, `nb_perdue`, `resumer`) VALUES
(1, 'La forêt enchantée', 0, 3, 9, 1, 8, 'Gérard, son petit fils Charlie, et son chien Fifi, partent pour une balade en forêt. Mais cette petite virée leur réserve bien des surprises ...'),
(2, 'TEST', 0, 4, 6, 6, 0, 'TEST');

-- Déchargement des données de la table `chapitre`
--

INSERT INTO `chapitre` (`id_ch_hors_hist`, `id_chapitre`, `titre`, `id_hist`, `type_fin`, `modif_vie`, `id_ch_choix1`, `id_ch_choix2`, `id_ch_choix3`, `choix1`, `choix2`, `choix3`, `textes`) VALUES
(15, 1, 'Départ', 1, NULL, 0, 2, 3, 4, 'Charlie', 'Gérard', 'Fifi', 'Cette histoire débute un après-midi de printemps.  Charlie, son grand père Gérard, et son chien Fifi arrive à l’orée du bois de leur village. \r\nQuel personnage souhaitez-vous incarner?'),
(16, 2, 'L\'étrange plante', 1, NULL, 0, 5, 6, 7, 'J’interroge mon grand père dessus, il aura surement une explication à me donner.', 'Je continue mon chemin tranquillement. Cela doit être une simple fougère.', 'Je la fait sentir à Fifi, il m’indiquera si elle est toxique.', 'Vous êtes très heureux de vous promener avec votre grand père, dont les nombreuses connaissances vous étonnent encore plus chaque jour. C’est alors que vous remarquez une étrange plante, que vous n’aviez jamais vu avant. Que décidez-vous de faire?'),
(17, 3, 'Gérard le savant', 1, NULL, -1, 8, 9, 10, 'Je les ramasse pour les cuisiner ce soir. Je connais bien ces champignons, dans une omelette ce sera exquis. ', 'Je n’y touche pas. Je n’accorde aucune confiance à ma mémoire quelque peu défaillante et ne souhaite pas m’intoxiquer.', 'Je les ramasse pour les examiner dans mon laboratoire.', 'Votre âge vous rend plus faible, vous perdez donc une vie. Vous decidez d’expliquer à votre  petit fils toutes vos connaissances sur la faune et la flore de cette forêt. Vous remarquez des champignons qui vous rappellent votre enfance. Que décidez-vous d’en faire?'),
(18, 4, 'La balade de Fifi', 1, NULL, 0, 11, 12, 13, 'Vous décidez de lui courrir après, tant pis pour Gérard et Charlie vous les retrouverez après.', 'Vous essayer de le croquer, ça n’a pas l’air mauvais après tout', 'Vous le laissez passer avec dédain, une si petite bête n’a déjà pas beaucoup de chance de survivre toute seule.', 'Cette balade en forêt vous réjouit grandement, dégourdir vos petites pattes est une une activité qui vous avait grandement manqué. \r\nUn campagnol attire votre attention.'),
(19, 5, 'L\'observation de la plante', 1, NULL, 0, 14, 15, 16, 'Vous décidez de la montrer à un vieux druide de votre village', 'Vous décidez de le montrer à un scientifique', 'Vous décidez de gouter en croquant dans la fleur. Votre papi vous a souvent expliqué que les pétales de de nombreuses fleurs étaient comestibles.', 'Après avoir observé longuement la plante, Papi Gérard avoue qu’il ne l’avais jamais vue. Pourtant, il habite près de cette forêt et vient s’y promener depuis qu’il est enfant. Cette plante devient donc encore plus intrigante.'),
(20, 6, 'Les lianes', 1, NULL, 0, 17, 18, 19, 'Vous poussez votre grand-père à s’y balancer, ça lui rappelera son enfance!', 'Vous vous balancez à une liane, imitant Tarzan', 'Vous accrochez votre chien à liane afin qu’il se balance', 'Vous continuez votre chemin paisiblement, et arrivez sous un saule pleureur dont les branches vous rapellent les lianes de Tarzan. Que décidez-vous de faire?'),
(21, 7, 'Fifi et la plante toxique', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A peine Fifi a mis sa truffe contre la mystérieuse plante, qu’il est tombé à la renverse. Cette plante semble toxique, vous décidez de prendre le chien dans vos bras et de vous en éloigner au plus vire. Cette balade a vite tourné à la catastrophe!'),
(22, 8, 'La cuisson des champignons', 1, NULL, 0, 20, 21, 22, '2 minutes, cela suffira', '7 minutes, il faut qu’ils grillent un peu', '15 minutes, je les aime bien cuits', 'Vous rentrez à la maison avec votre petite tribue toute souillée., l’omelette de ce soir en perspective.\r\nAprès quelques minutes à laisser mijoter ce bon plat quelques minutes avant de passer à table. Combien de temps faites-vous cuire ces champignons?'),
(23, 9, 'Les lianes de Tarzan', 1, NULL, 0, 23, 24, 25, 'Vous vous balancez à une liane, imitant Tarzan', 'Vous accrochez votre petit-fils à la liane afin qu’il se balance', 'Vous accrochez votre chien à liane afin qu’il se balance', 'Quelle sage décision! Vous poursuivez donc la balade, et arrivez sous un saule pleureur dont les branches vous rapelles les lianes de Tarzan. Que décidez-vous de faire?'),
(24, 10, 'L\'analyse au laboratoire', 1, NULL, 0, 26, 27, 28, 'J’observe ce jus au microscope', 'J’examine la composition du jus', 'Je craque et finit par manger ma bouille de champignons cuits', 'Je les cuits et les broie pour en tirer du jus. Que décidez vous d\'en faire ensuite?'),
(25, 11, 'La famille de la plaine', 1, NULL, 0, 29, 30, 31, 'Vous ne vous faites pas trop de soucis, cette nouvelle famille vous donnera peut-être plus de friandises', 'Vous hurlez pour pousser ces inconnus à bout et qu’ils vous relachent', 'Vous restez calme, votre famille finira bien par venir vous chercher', 'Vous perdez vite la petite bête de vue, mais découvrez une grande étandue d’herbe, avec une fontaine au milieu. Des dizaines de chiens y jouent avec leurs maitres et vous décidez de vous joindre à eux. Un enfant se met gentillement à jouer avec vous, en vous lançant un baton, ce qui vous rend très joyeux. Après plusieurs minutes de jeux, ses parents viennent le chercher, et il insiste pour vous garder. C’est ainsi que vous vous retrouvez embarqué dans la voiture d’une famille inconnue. Zut! Gérard et charlie vont d’inquiéter.'),
(26, 12, 'Le fail du campagnol', 1, NULL, -1, 32, 33, 34, 'Vous partez en courant devant Gérard et Charlie.', 'Vous restez sage mais cela vous frustre', 'Vous faites des tours autour de vos maitres, tout agité.', 'Vous vous jetez sur la bestiole, ouvrez la geule et la refermez de toute vos forces, pensant la croquer. Mais le rongeur a filé à toute vitesse et vos dents s’entrechoquent bruyamment. Vous perdez une vie. Sonné, vous titubez, et reprennez lentement la ballade avec vos maitres. Cette ballade est trop lente pour vous.'),
(27, 13, 'L\'attaque du campagnol', 1, NULL, -1, 35, 36, 37, 'Vous faites comme si de rien était. C’est vraiment la honte de se faire attaquer par une si petite bête.', 'Vous poussez un cri qui alerte vos maitres. Ceux-cis décident de vous emmener aux urgences vétérinaires.', 'Vous lèchez la plaie dans l’espoir d’arreter le saignement.', 'Votre bonté vous perdra. La petite bête se jette sur vous et vous mord la patte! Vous perdez une vie. Le sang perle déjà sur la plaie dévoilée par les crocs du rongeur, qui s’est aussitôt enfuit.'),
(28, 14, 'Le méchant druide', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Il vous rejette et vous traite de sorciers fous! Appeuré, il vous jette un sors pour vous emprisonner.'),
(29, 15, 'Le scientifique ravi', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Il vous accueille gentiment, et après analyse il vous consiède comme des dieux car vous venez de lui ramener une plante très rare., qui va l’aider dans ses recherches.'),
(30, 16, 'La degustation de la fleur', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Vous tombez raide mort. Cette plante était toxique'),
(31, 17, 'La blessure de Papi', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Zut! Son poids fait  craquer la liane, et ses vieux os ne permettent pas de soutenir son corps. Il se tord la cheville Vous avez gaché la journée.'),
(32, 18, 'L\'amusement de Charlie', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quelle bonne idée! \r\nVous vous amusez comme un petit fou! Cela a refait votre journée!'),
(33, 19, 'Fifi et la liane serpent', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Misère! La liane était en réalité un serpent! Votre chien se fait mordre!'),
(34, 20, 'La mauvaise cuisson', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ces champignons ne devaient pas être les délicieux champignons de votre enfance. Aussi peu cuits, ils sont très dangereux. Ce délicieux repas sera votre dernier.'),
(35, 21, 'Une cuisson trop longue', 1, NULL, -1, 38, 39, 40, 'Brice de Nice 3', 'Astérix et Obélix: Mission Cléopatre', 'Un film d’horreur slovaque', 'Les champignons ont trop cuit, vous mangez un petit peu de champignon carbonisé, ce qui est mauvais pour la santé. Vous perdez 1 point de vie. Malgré une digestion compliquée, la soirée poursuit son cours. Vous vous battez pour choisir un film et finalement 3 choix s’oposent :'),
(36, 22, 'La cuisson particulière', 1, NULL, 0, 41, 42, 43, 'Vous vous jetez dessus pour la caresser', 'Vous décidez de sortir de la boîte ppour prendre l’air. Prenant conscience que ce n’est pas normal', 'Vous continuez à danser sur la piste. Ce n’est que dans votre tête, elle va partir!', 'La cuisson particulière de ces champignons semble avoir libébré meurs propriétés hallucinogènes et euphorisantes. Pris d’une énergie folle, vous décidez d’emmener votre femme Geneviève en boîte de nuit. \r\nVous entrez dans un lieu chaud et bruyant, et prenez un cocktail alcoolisé. Les champignons vous font provoquent des hallucinations. Vous voyez une Licorne au fond de la pièce.\r\n'),
(37, 23, 'La cheville ', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Votre poids fait  craquer la liane, et vos vieux os ne permettent de soutenir votre corps. Vous vous tordez la cheville et gachez la journée.'),
(38, 24, 'Charlie et la liane', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quelle bonne idée! \r\nCharlie s’amuse comme un petit fou! Son bonheur vous a empli de joie. \r\nQuelle belle journée!'),
(39, 25, 'La liane et Fifi', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Misère! La liane était en réalité un serpent! Votre chien se fait mordre. '),
(40, 26, 'Le jus vivant', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Le jus de ces champignons grouille d’organismes vivants. Ce n’est pas normal d’en voir autant, surtout après une telle cuisson. Les vapeurs s’émanant du jus sont très odorantes et embaument très vite la pièce. Malheureusement, vous vous rendez compte un peu trop tard qu’elles sont toxiques...'),
(41, 27, 'Les molécules', 1, NULL, 0, 44, 45, 46, 'Je décide d’en parler tout de suite à un vieux collègue scientifique pour avoir son avis. ', 'Je garde ça pour moi, je ne veux pas que le monde scientifique décime tous les champignons de la forêt pour comprendre d’où viennent ces molécules extraterrestres', 'Je décide de continuer mes analyses pour rédiger un article scientifique révélant au grand jour ma découverte', 'J’y trouve des molécules étranges, qui ne sont pas sensées être présentes sur Terre. En effet ces molécules sont extraterrestre et ont saulement été observées sur Mars.\r\nEbahit par cette découverte, vous prenez un moment pour réaliser et réflichissez à ce que vous allez en faire.'),
(42, 28, 'La boite', 1, NULL, 0, 47, 48, 49, 'Vous vous jetez dessus pour la caresser', 'Vous décidez de sortir de la boîte ppour prendre l’air. Prenant conscience que ce n’est pas normal', 'Vous continuez à danser sur la piste. Ce n’est que dans votre tête, elle va partir!', 'La cuisson particulière de ces champignons semble avoir libébré meurs propriétés hallucinogènes et euphorisantes. Pris d’une énergie folle, vous décidez d’emmener votre femme Geneviève en boîte de nuit. \r\nVous entrez dans un lieu chaud et bruyant, et prenez un cocktail alcoolisé. Les champignons vous font provoquent des hallucinations. Vous voyez une Licorne au fond de la pièce.\r\n'),
(43, 29, 'Le chien heureux', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Vous vivez une vie heureuse dans cette nouvelle famille et êtes chouchouté comme un roi'),
(44, 30, 'Le chien volant', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Il finissent par s’enerver et vous jeter par la fenêtre. Vous auriez peut-être dû vous taire.'),
(45, 31, 'Le retour de la famille', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Après queslques heures chez ces inconnus, une voiture arrive dans leur allée. C’est Gérard et Charlie qui viennent vous récupérer. Ouf!'),
(46, 32, 'Le ravin', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Vous ne percevez pas le danger devant vous et tombez dans un ravin'),
(47, 33, 'Le chien parfait', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'La virée en forêt se finit paisiblement et vous êtes chouchouté au retour à la maison. Vous avez bien fait de rester sage.'),
(48, 34, 'Le mauvais chien', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ils se fachent et écourtent la ballade. Vous n’aurez pas de friandises ce soir.'),
(49, 35, 'La rage', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Malheureusement, le rongeur avait la rage et la maladie vous terrassera dans les semaines qui suivent'),
(50, 36, 'Le véto', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ils ont bien fait de vous y emmener, après quelques soins, vous rentrez chez-vous et on vous donne des friandises'),
(51, 37, 'SuperFifi', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'La morsure de ce rongeur vous procure des pouvoirs magiques innatendus. Vous devenez un super chien, prêt à tout pour sauver tous ses comparses de l’abandon.'),
(52, 38, 'Le mauvais film', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quel mauvais choix, cette décision vous fais perdre!'),
(53, 39, 'Le bon film', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quel bon choix vous avez réussi à faire de cette soirée, l’un des meilleurs souvenirs de votre vie!'),
(54, 40, 'Le film effrayant', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ce film était trop violent pour vous, un moment d\'épouvante vous provoque une crise cardiaque!'),
(55, 41, 'La licorne inexistante', 1, NULL, -1, 50, 51, 52, 'Vous prenez la voiture, la route sera rapide à faire, et les effets de l’alcool et des champignons semblent dissipés, vous ne risquez pas grand chose', 'Vous décidez de rentrer à pied, la route sera un peu longue, mais c’est plus sûr', 'Vous voyez des bornes pour emprunter des vélos, et décidez d’en utiliser pour faire la route jusqu’à chez-vous', 'C’était évidemment une illusion, vous tombez en croyant vous appuyer sur elle. Votre tête heurte une banquette, et vous tombez assomé. Vous perdez une vie.\r\nVous vous réveillez une heure plus tard, dans une petite pièce du club. Vous décidez de rentrer chez vous.'),
(56, 42, 'L\'aventure', 1, NULL, 0, 53, 54, 55, 'Vous prenez la voiture, la route sera rapide à faire, et les effets de l’alcool et des champignons semblent dissipés, vous ne risquez pas grand chose', 'Vous décidez de rentrer à pied, la route sera un peu longue, mais c’est plus sûr', 'Vous voyez des bornes pour emprunter des vélos, et décidez d’en utiliser pour faire la route jusqu’à chez-vous', 'Vous partez à l’aventure dans les rues, avec Geneviève, comme au bon vieux temps. Puis décidez de rentrer chez vous.'),
(57, 43, 'La licorne magique', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Au bout de plusieurs heures, bien que les effets des champignons se dissipent, la licorne est toujours là. De plus d’autres personnes dans la boite l’ont vue et la caressent. Vous décidez alors de vous en approcher. Alors que vous tentez de l’aborder, vous vous rendez compte que la licorne comprend votre langage. Elle vous invite à partir à l’aventure avec elle. vous la chevauchez donc et partez à la découverte de son monde: la planète des arcs en ciel et des nuages en Barbapapa ...'),
(58, 44, 'Le scientifique malhonnête', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ce collègue vous trahit et brise ainsi votre coeur. Il révèle cette découverte en se faisant passer pour le génie de l’histoire. Cela vous achève.'),
(59, 45, 'La sauvegarde des champignons', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quelle bonne idée, vous poursuivez votre vie paisiblement, en ayant la possibilité, au cours de vos sorties en forêt, de profiter de ces magnifiques champignons.'),
(60, 46, 'L\'article glorieux', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Cette article vous fait connaitre dans tous le monde scientifique et vous procure gloire et bonheur. Vous passez une fin de vie heureuse à parler de vos recherches dans les plus grands congrès aux quatre coins du monde'),
(61, 47, 'La fausse licorne', 1, NULL, -1, 56, 57, 58, 'Vous prenez la voiture, la route sera rapide à faire, et les effets de l’alcool et des champignons semblent dissipés, vous ne risquez pas grand chose', 'Vous décidez de rentrer à pied, la route sera un peu longue, mais c’est plus sûr', 'Vous voyez des bornes pour emprunter des vélos, et décidez d’en utiliser pour faire la route jusqu’à chez-vous', 'C’était évidemment une illusion, vous tombez en croyant vous appuyer sur elle. Votre tête heurte une banquette, et vous tombez assomé. Vous perdez une vie.\r\nVous vous réveillez une heure plus tard, dans une petite pièce du club. Vous décidez de rentrer chez vous.'),
(62, 48, 'Le bon vieux temps', 1, NULL, 0, 59, 60, 61, 'Vous prenez la voiture, la route sera rapide à faire, et les effets de l’alcool et des champignons semblent dissipés, vous ne risquez pas grand chose', 'Vous décidez de rentrer à pied, la route sera un peu longue, mais c’est plus sûr', 'Vous voyez des bornes pour emprunter des vélos, et décidez d’en utiliser pour faire la route jusqu’à chez-vous', 'Vous partez à l’aventure dans les rues, avec Geneviève, comme au bon vieux temps. Puis décidez de rentrer chez vous.'),
(63, 49, 'Le monde parallèle', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Au bout de plusieurs heures, bien que les effets des champignons se dissipent, la licorne est toujours là. De plus d’autres personnes dans la boite l’ont vue et la caressent. Vous décidez alors de vous en approcher. Alors que vous tentez de l’aborder, vous vous rendez compte que la licorne comprend votre langage. Elle vous invite à partir à l’aventure avec elle. vous la chevauchez donc et partez à la découverte de son monde: la planète des arcs en ciel et des nuages en Barbapapa ...'),
(64, 50, 'L\'accident', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(65, 51, 'Le piéton malade', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants. Mais le chemin est long, et le froid et l’humidité de la nuit vous rends malade.\r\nVous perdez une vie. \r\n'),
(66, 52, 'L\'équilibre délicat', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Encore sous l’emprise de l’alcool, vous basculez à la renverse et vous éraflez toute la cuisse. Vous perdez une vie.\r\n'),
(67, 53, 'Le virage', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(68, 54, 'Le piéton chanceux', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants.Vous rentrez sein et sauf. Ce petit périple vous aura appris une bonne leçon. Et oui, à votre âge on apprends encore, et vous ne toucherez plus de si tôt à des champignons'),
(69, 55, 'La chute du vélo', 1, NULL, -1, 62, 63, 64, 'Je continue à pieds, c’est plus prudent!', 'Je remonte sur le vélo avec fierté, heureusement, personne ne m’a vu tomber', 'Je remonte sur le vélo avec fierté, heureusement, personne ne m’a vu tomber', 'Encore sous l’emprise de l’alcool, vous basculez à la renverse et vous éraflez toute la cuisse. Vous perdez une vie.'),
(70, 56, 'L\'accident fatal', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(71, 57, 'Rentrer malade', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants. Mais le chemin est long, et le froid et l’humidité de la nuit vous rends malade.\r\nVous perdez une vie. \r\n'),
(72, 58, 'Le cycliste maladroit', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Encore sous l’emprise de l’alcool, vous basculez à la renverse et vous éraflez toute la cuisse. Vous perdez une vie.'),
(73, 59, 'Des substances fatales', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(74, 60, 'La bonne décision', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants.Vous rentrez sein et sauf. Ce petit périple vous aura appris une bonne leçon. Et oui, à votre âge on apprends encore, et vous ne toucherez plus de si tôt à des champignons'),
(75, 61, 'L\'emprise sur le cycliste', 1, NULL, -1, 65, 66, 67, 'Je continue à pieds, c’est plus prudent!', 'Je remonte sur le vélo avec fierté, heureusement, personne ne m’a vu tomber', 'Je remonte sur le vélo avec fierté, heureusement, personne ne m’a vu tomber', 'Encore sous l’emprise de l’alcool, vous basculez à la renverse et vous éraflez toute la cuisse. Vous perdez une vie.'),
(76, 62, 'La leçon', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants.Vous rentrez sein et sauf. Ce petit périple vous aura appris une bonne leçon. Et oui, à votre âge on apprends encore, et vous ne toucherez plus de si tôt à des champignons.'),
(77, 63, 'L\'arbre fatal', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(78, 64, 'Le poignet', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Vous basculez à nouveau, et vous blessez au poignet, définitivement cette soirée n’était pas la votre.'),
(79, 65, 'La sage décision', 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'C’est une sage décision, car vous êtes toujours titubants.Vous rentrez sein et sauf. Ce petit périple vous aura appris une bonne leçon. Et oui, à votre âge on apprends encore, et vous ne toucherez plus de si tôt à des champignons'),
(80, 66, 'La dernière soirée', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Visiblement, les substances que vous aviez consommées étaient coriaces, et vos réflexes étaient encore annihilés. Vous ratez un virage, et percutez un arbre. Cet accident vous est malheureusement fatal, et cette folle soirée restera votre dernière'),
(81, 67, 'La bascule', 1, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Vous basculez à nouveau, et vous blessez au poignet, définitivement cette soirée n’était pas la votre'),
(201, 1, 'ONE', 2, NULL, 0, 2, 3, 4, 'DEUX', 'TROIS', 'QUATRE', 'ONE'),
(202, 2, 'DEUX', 2, NULL, 0, 5, 3, 4, 'CINQ', 'TROISBIS', 'QUATREBIS', 'DEUX'),
(203, 3, 'TROIS', 2, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'TROIS'),
(204, 4, 'QUATRE', 2, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'QUATRE'),
(205, 5, 'CINQ', 2, 0, -2, NULL, NULL, NULL, NULL, NULL, NULL, 'CINQ');

COMMIT;
